import BaseDocument from "./base";

export default function TermsOfUse() {
  return (
    <BaseDocument>
      <p>
        For the sake of this agreement, Us, We, and Our refers to Conversation
        and its collective developers or operators. You refers to you, the user
        of this product accessing it through Our website.
      </p>
      <p>
        This is just the beta, so I&apos;ll keep it short. There are a couple of
        big things:
      </p>
      <ul>
        <li>
          We <b>are not responsible</b> for anything that happens on this
          platform, in beta or published.
        </li>
        <li>
          By using this service, you acknowledge that all data generated by You
          may be lost at any time due to Our incompetence.
        </li>
        <li>
          You agree that you will not generate vulgar or inappropriate content.
        </li>
        <li>
          You acknowledge that your access may be removed at any time, with or
          without consent.
        </li>
      </ul>
      <p>Also note:</p>
      <pre style={{ whiteSpace: "pre-wrap" }}>
        Permission is hereby granted, free of charge, to any person obtaining a
        copy of this software and associated documentation files (the
        &quot;Software&quot;), to deal in the Software without restriction,
        including without limitation the rights to use, copy, modify, merge,
        publish, distribute, sublicense, and/or sell copies of the Software, and
        to permit persons to whom the Software is furnished to do so, subject to
        the following conditions: The above copyright notice and this permission
        notice shall be included in all copies or substantial portions of the
        Software.
        <br />
        THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY
        KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
        IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
        CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
        TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
        SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
      </pre>
    </BaseDocument>
  );
}
